#!/bin/bash
# OwlsHook - Push to GitHub
# Run these commands manually

echo "🦉 OwlsHook - GitHub Push Instructions"
echo "======================================"
echo ""
echo "1. Install GitHub CLI (if not installed):"
echo "   sudo apt install gh"
echo ""
echo "2. Login to GitHub:"
echo "   gh auth login"
echo ""
echo "3. Create repository and push:"
echo "   cd ~/owlshook"
echo ""
echo "   gh repo create owlshook \\"
echo "     --public \\"
echo "     --description 'Professional OSINT & Digital Forensics Toolkit - GPS extraction, AI detection, server geolocation, video analysis' \\"
echo "     --source . \\"
echo "     --remote origin \\"
echo "     --push \\"
echo "     -- \\"
echo "     cybersecurity osint forensics digital-forensics \\"
echo "     metadata exif gps image-analysis video-analysis \\"
echo "     ai-detection geolocation python cli-tool infosec \\"
echo "     penetration-testing security-tools investigation \\"
echo "     threat-intelligence incident-response digital-investigation"
echo ""
echo "4. Or manually create repo on GitHub then:"
echo "   git remote add origin https://github.com/keiz7en/owlshook.git"
echo "   git push -u origin main"
echo ""
echo "5. Add topics via GitHub web:"
echo "   https://github.com/keiz7en/owlshook/edit"
echo "   Scroll to 'Topics' and add:"
echo "   cybersecurity, osint, forensics, digital-forensics,"
echo "   metadata, exif, gps, image-analysis, video-analysis,"
echo "   ai-detection, geolocation, python, cli-tool, infosec,"
echo "   penetration-testing, security-tools, investigation,"
echo "   threat-intelligence, incident-response, digital-investigation"
echo ""
echo "🏷️  Hashtags for social media:"
echo "   #cybersecurity #osint #forensics #metadata #exif"
echo "   #gps #imageanalysis #videanalysis #aiedetection"
echo "   #geolocation #python #clitool #infosec #security"
echo ""
echo "🦉 Ready to push!"
